# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import bank_pb2 as bank__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in bank_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BankServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetBalance = channel.unary_unary(
                '/bank.BankService/GetBalance',
                request_serializer=bank__pb2.BalanceRequest.SerializeToString,
                response_deserializer=bank__pb2.BalanceResponse.FromString,
                _registered_method=True)
        self.Deposit = channel.unary_unary(
                '/bank.BankService/Deposit',
                request_serializer=bank__pb2.TransactionRequest.SerializeToString,
                response_deserializer=bank__pb2.TransactionResponse.FromString,
                _registered_method=True)
        self.Withdraw = channel.unary_unary(
                '/bank.BankService/Withdraw',
                request_serializer=bank__pb2.TransactionRequest.SerializeToString,
                response_deserializer=bank__pb2.TransactionResponse.FromString,
                _registered_method=True)
        self.TransferLocal = channel.unary_unary(
                '/bank.BankService/TransferLocal',
                request_serializer=bank__pb2.TransferRequest.SerializeToString,
                response_deserializer=bank__pb2.TransferResponse.FromString,
                _registered_method=True)
        self.Prepare = channel.unary_unary(
                '/bank.BankService/Prepare',
                request_serializer=bank__pb2.PrepareRequest.SerializeToString,
                response_deserializer=bank__pb2.PrepareResponse.FromString,
                _registered_method=True)
        self.Commit = channel.unary_unary(
                '/bank.BankService/Commit',
                request_serializer=bank__pb2.CommitRequest.SerializeToString,
                response_deserializer=bank__pb2.CommitResponse.FromString,
                _registered_method=True)
        self.Abort = channel.unary_unary(
                '/bank.BankService/Abort',
                request_serializer=bank__pb2.AbortRequest.SerializeToString,
                response_deserializer=bank__pb2.AbortResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/bank.BankService/Heartbeat',
                request_serializer=bank__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=bank__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.Election = channel.unary_unary(
                '/bank.BankService/Election',
                request_serializer=bank__pb2.ElectionRequest.SerializeToString,
                response_deserializer=bank__pb2.ElectionResponse.FromString,
                _registered_method=True)
        self.Coordinator = channel.unary_unary(
                '/bank.BankService/Coordinator',
                request_serializer=bank__pb2.CoordinatorRequest.SerializeToString,
                response_deserializer=bank__pb2.CoordinatorResponse.FromString,
                _registered_method=True)
        self.GetEvents = channel.unary_unary(
                '/bank.BankService/GetEvents',
                request_serializer=bank__pb2.EventsRequest.SerializeToString,
                response_deserializer=bank__pb2.EventsResponse.FromString,
                _registered_method=True)
        self.SetNodeStatus = channel.unary_unary(
                '/bank.BankService/SetNodeStatus',
                request_serializer=bank__pb2.NodeStatusRequest.SerializeToString,
                response_deserializer=bank__pb2.NodeStatusResponse.FromString,
                _registered_method=True)


class BankServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GetBalance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Deposit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Withdraw(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TransferLocal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Prepare(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Commit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Abort(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Election(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Coordinator(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetNodeStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BankServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetBalance': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBalance,
                    request_deserializer=bank__pb2.BalanceRequest.FromString,
                    response_serializer=bank__pb2.BalanceResponse.SerializeToString,
            ),
            'Deposit': grpc.unary_unary_rpc_method_handler(
                    servicer.Deposit,
                    request_deserializer=bank__pb2.TransactionRequest.FromString,
                    response_serializer=bank__pb2.TransactionResponse.SerializeToString,
            ),
            'Withdraw': grpc.unary_unary_rpc_method_handler(
                    servicer.Withdraw,
                    request_deserializer=bank__pb2.TransactionRequest.FromString,
                    response_serializer=bank__pb2.TransactionResponse.SerializeToString,
            ),
            'TransferLocal': grpc.unary_unary_rpc_method_handler(
                    servicer.TransferLocal,
                    request_deserializer=bank__pb2.TransferRequest.FromString,
                    response_serializer=bank__pb2.TransferResponse.SerializeToString,
            ),
            'Prepare': grpc.unary_unary_rpc_method_handler(
                    servicer.Prepare,
                    request_deserializer=bank__pb2.PrepareRequest.FromString,
                    response_serializer=bank__pb2.PrepareResponse.SerializeToString,
            ),
            'Commit': grpc.unary_unary_rpc_method_handler(
                    servicer.Commit,
                    request_deserializer=bank__pb2.CommitRequest.FromString,
                    response_serializer=bank__pb2.CommitResponse.SerializeToString,
            ),
            'Abort': grpc.unary_unary_rpc_method_handler(
                    servicer.Abort,
                    request_deserializer=bank__pb2.AbortRequest.FromString,
                    response_serializer=bank__pb2.AbortResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=bank__pb2.HeartbeatRequest.FromString,
                    response_serializer=bank__pb2.HeartbeatResponse.SerializeToString,
            ),
            'Election': grpc.unary_unary_rpc_method_handler(
                    servicer.Election,
                    request_deserializer=bank__pb2.ElectionRequest.FromString,
                    response_serializer=bank__pb2.ElectionResponse.SerializeToString,
            ),
            'Coordinator': grpc.unary_unary_rpc_method_handler(
                    servicer.Coordinator,
                    request_deserializer=bank__pb2.CoordinatorRequest.FromString,
                    response_serializer=bank__pb2.CoordinatorResponse.SerializeToString,
            ),
            'GetEvents': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEvents,
                    request_deserializer=bank__pb2.EventsRequest.FromString,
                    response_serializer=bank__pb2.EventsResponse.SerializeToString,
            ),
            'SetNodeStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.SetNodeStatus,
                    request_deserializer=bank__pb2.NodeStatusRequest.FromString,
                    response_serializer=bank__pb2.NodeStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'bank.BankService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('bank.BankService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BankService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetBalance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bank.BankService/GetBalance',
            bank__pb2.BalanceRequest.SerializeToString,
            bank__pb2.BalanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Deposit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bank.BankService/Deposit',
            bank__pb2.TransactionRequest.SerializeToString,
            bank__pb2.TransactionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Withdraw(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bank.BankService/Withdraw',
            bank__pb2.TransactionRequest.SerializeToString,
            bank__pb2.TransactionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TransferLocal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bank.BankService/TransferLocal',
            bank__pb2.TransferRequest.SerializeToString,
            bank__pb2.TransferResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Prepare(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bank.BankService/Prepare',
            bank__pb2.PrepareRequest.SerializeToString,
            bank__pb2.PrepareResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Commit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bank.BankService/Commit',
            bank__pb2.CommitRequest.SerializeToString,
            bank__pb2.CommitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Abort(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bank.BankService/Abort',
            bank__pb2.AbortRequest.SerializeToString,
            bank__pb2.AbortResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bank.BankService/Heartbeat',
            bank__pb2.HeartbeatRequest.SerializeToString,
            bank__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Election(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bank.BankService/Election',
            bank__pb2.ElectionRequest.SerializeToString,
            bank__pb2.ElectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Coordinator(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bank.BankService/Coordinator',
            bank__pb2.CoordinatorRequest.SerializeToString,
            bank__pb2.CoordinatorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bank.BankService/GetEvents',
            bank__pb2.EventsRequest.SerializeToString,
            bank__pb2.EventsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetNodeStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bank.BankService/SetNodeStatus',
            bank__pb2.NodeStatusRequest.SerializeToString,
            bank__pb2.NodeStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
